config/routes.rb
Rails.application.routes.draw do
  resources :register_coffes
  get 'home/index'
  root 'home#index'

  devise_for :employees, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/register_coffe.rb
class RegisterCoffe < ApplicationRecord
  belongs_to :coffe
  belongs_to :employee  
end

app/controllers/register_coffes_controller.rb
class RegisterCoffesController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_register_coffe, only: [:show, :edit, :update, :destroy]


  # GET /register_coffes
  # GET /register_coffes.json
  def index
    @register_coffes = RegisterCoffe.all
  end

  # GET /register_coffes/1
  # GET /register_coffes/1.json
  def show
  end

  # GET /register_coffes/new
  def new
    @register_coffe = current_employee.register_coffes.build
    @coffe = take_coffe_for_user
  end

  # GET /register_coffes/1/edit
  def edit
  end

  # POST /register_coffes
  # POST /register_coffes.json
  def create
    @register_coffe = current_employee.register_coffes.build(register_coffe_params)

    respond_to do |format|
      if @register_coffe.save
        format.html { redirect_to register_coffes_path, notice: 'Tudo certo, aproveita o café ai champs!' }
        format.json { render :index, status: :created, location: @register_coffe }
      else
        format.html { render :new }
        format.json { render json: @register_coffe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /register_coffes/1
  # PATCH/PUT /register_coffes/1.json
  def update
    respond_to do |format|
      if @register_coffe.update(register_coffe_params)
        format.html { redirect_to register_coffes_path, notice: 'Tudo certo, aproveita o café ai champs.' }
        format.json { render :index, status: :ok, location: @register_coffe }
      else
        format.html { render :edit }
        format.json { render json: @register_coffe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /register_coffes/1
  # DELETE /register_coffes/1.json
  def destroy
    @register_coffe.destroy
    respond_to do |format|
      format.html { redirect_to register_coffes_url, notice: 'Tudo certo, aproveita o café ai champs.' }
      format.json { head :no_content }
    end
  end

  private
    def verify_if_user_is_special
      current_employee.special?
    end

    def take_coffe_for_user
      if verify_if_user_is_special
        Coffe.all()
      else
        Coffe.where(special: false)
      end
    end

    
    # Use callbacks to share common setup or constraints between actions.
    def set_register_coffe
      @register_coffe = RegisterCoffe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_coffe_params
      params.require(:register_coffe).permit(:coffe_id, :employee_id, :date)
    end
end

app/helpers/register_coffes_helper.rb
module RegisterCoffesHelper
end

app/views/register_coffes/_form.html.erb
<%= form_with(model: register_coffe, local: true,html: {class:'border form-subscribe p-4'}) do |form| %>
  <% if register_coffe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register_coffe.errors.count, "error") %> Não foi possivel salvar</h2>

      <ul>
      <% register_coffe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :café %>
    <%= collection_select :register_coffe, :coffe_id, @coffe , :id, :name,{}, {:class => "form-control"} %>
  </div>


  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_select :date, {:start_year => 2017,:end_year => 2018,  :minute_step => 10 } %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: 'btn btn-primary' %>
    <%= link_to 'Voltar', register_coffes_path, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/register_coffes/edit.html.erb
<h1>Editing Register Coffe</h1>

<%= render 'form', register_coffe: @register_coffe %>

<%= link_to 'Show', @register_coffe %> |
<%= link_to 'Back', register_coffes_path %>

app/views/register_coffes/index.html.erb
<script>
$.notify("<%= notice %>", "success")
</script>
<%= link_to  "Logout", destroy_employee_session_path, method: :delete, class: 'btn btn-outline-secondary float-right mt-3'  %>
<h1 class="text-center">  Cafés pegos</h1>

<%= link_to 'Pegar café', new_register_coffe_path, class: 'btn btn-primary mb-3' %>


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Café</th>
      <th scope="col">Funcionário</th>
      <th scope="col">Cargo</th>
      <th scope="col">E-mail</th>
      <th scope="col">Data</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @register_coffes.each do |register_coffe| %>
      <tr>
        <td><%= register_coffe.coffe.name %></td>
        <td><%= register_coffe.employee.name %></td>
        <td><%= register_coffe.employee.position %></td>
        <td><%= register_coffe.employee.email %></td>
        <td><%= register_coffe.date.to_time.strftime('%d/%m/%Y %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/register_coffes/new.html.erb
<h1 class="text-center">Registrar café</h1>

<%= render 'form', register_coffe: @register_coffe %>